print('http://hz.mit.edu/009_lab9/cat_poster.jpg-part0\nhttp://smatz.net/009_lab9/cat_poster.jpg-part0\nhttp://scripts.mit.edu/~6.009/lab9/redir.py/0/cat_poster.jpg-part0\nhttp://scripts.mit.edu/~6.009/lab9/occasional_error.py/cat_poster.jpg-part0\nhttp://mit.edu/6.009/www/lab9_examples/cat_poster.jpg-part0\n--\nhttp://hz.mit.edu/009_lab9/cat_poster.jpg-part1\nhttp://smatz.net/009_lab9/cat_poster.jpg-part1\nhttp://scripts.mit.edu/~6.009/lab9/redir.py/0/cat_poster.jpg-part1\nhttp://scripts.mit.edu/~6.009/lab9/occasional_error.py/cat_poster.jpg-part1\nhttp://mit.edu/6.009/www/lab9_examples/cat_poster.jpg-part1\n--\nhttp://hz.mit.edu/009_lab9/cat_poster.jpg-part2\nhttp://smatz.net/009_lab9/cat_poster.jpg-part2\nhttp://scripts.mit.edu/~6.009/lab9/redir.py/0/cat_poster.jpg-part2\nhttp://scripts.mit.edu/~6.009/lab9/occasional_error.py/cat_poster.jpg-part2\nhttp://mit.edu/6.009/www/lab9_examples/cat_poster.jpg-part2\n--\nhttp://hz.mit.edu/009_lab9/cat_poster.jpg-part3\nhttp://smatz.net/009_lab9/cat_poster.jpg-part3\nhttp://scripts.mit.edu/~6.009/lab9/redir.py/0/cat_poster.jpg-part3\nhttp://scripts.mit.edu/~6.009/lab9/occasional_error.py/cat_poster.jpg-part3\nhttp://mit.edu/6.009/www/lab9_examples/cat_poster.jpg-part3\n--\nhttp://hz.mit.edu/009_lab9/cat_poster.jpg-part4\nhttp://smatz.net/009_lab9/cat_poster.jpg-part4\nhttp://scripts.mit.edu/~6.009/lab9/redir.py/0/cat_poster.jpg-part4\nhttp://scripts.mit.edu/~6.009/lab9/occasional_error.py/cat_poster.jpg-part4\nhttp://mit.edu/6.009/www/lab9_examples/cat_poster.jpg-part4\n--\nhttp://hz.mit.edu/009_lab9/cat_poster.jpg-part5\nhttp://smatz.net/009_lab9/cat_poster.jpg-part5\nhttp://scripts.mit.edu/~6.009/lab9/redir.py/0/cat_poster.jpg-part5\nhttp://scripts.mit.edu/~6.009/lab9/occasional_error.py/cat_poster.jpg-part5\nhttp://mit.edu/6.009/www/lab9_examples/cat_poster.jpg-part5\n')
"""
http://hz.mit.edu/009_lab9/cat_poster.jpg-part0
http://smatz.net/009_lab9/cat_poster.jpg-part0
http://scripts.mit.edu/~6.009/lab9/redir.py/0/cat_poster.jpg-part0
http://scripts.mit.edu/~6.009/lab9/occasional_error.py/cat_poster.jpg-part0
http://mit.edu/6.009/www/lab9_examples/cat_poster.jpg-part0
--
http://hz.mit.edu/009_lab9/cat_poster.jpg-part1
http://smatz.net/009_lab9/cat_poster.jpg-part1
http://scripts.mit.edu/~6.009/lab9/redir.py/0/cat_poster.jpg-part1
http://scripts.mit.edu/~6.009/lab9/occasional_error.py/cat_poster.jpg-part1
http://mit.edu/6.009/www/lab9_examples/cat_poster.jpg-part1
--
http://hz.mit.edu/009_lab9/cat_poster.jpg-part2
http://smatz.net/009_lab9/cat_poster.jpg-part2
http://scripts.mit.edu/~6.009/lab9/redir.py/0/cat_poster.jpg-part2
http://scripts.mit.edu/~6.009/lab9/occasional_error.py/cat_poster.jpg-part2
http://mit.edu/6.009/www/lab9_examples/cat_poster.jpg-part2
--
http://hz.mit.edu/009_lab9/cat_poster.jpg-part3
http://smatz.net/009_lab9/cat_poster.jpg-part3
http://scripts.mit.edu/~6.009/lab9/redir.py/0/cat_poster.jpg-part3
http://scripts.mit.edu/~6.009/lab9/occasional_error.py/cat_poster.jpg-part3
http://mit.edu/6.009/www/lab9_examples/cat_poster.jpg-part3
--
http://hz.mit.edu/009_lab9/cat_poster.jpg-part4
http://smatz.net/009_lab9/cat_poster.jpg-part4
http://scripts.mit.edu/~6.009/lab9/redir.py/0/cat_poster.jpg-part4
http://scripts.mit.edu/~6.009/lab9/occasional_error.py/cat_poster.jpg-part4
http://mit.edu/6.009/www/lab9_examples/cat_poster.jpg-part4
--
http://hz.mit.edu/009_lab9/cat_poster.jpg-part5
http://smatz.net/009_lab9/cat_poster.jpg-part5
http://scripts.mit.edu/~6.009/lab9/redir.py/0/cat_poster.jpg-part5
http://scripts.mit.edu/~6.009/lab9/occasional_error.py/cat_poster.jpg-part5
http://mit.edu/6.009/www/lab9_examples/cat_poster.jpg-part5
"""